[package]
name = "wisdom"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
burn = { version = "0.16", features = ["wgpu", "ndarray", "train"] }
crossbeam-channel = "0.5"
rand = "0.8"

[[bin]]
name = "gui"
path = "src/bin/gui.rs"

[[bin]]
name = "selfplay"
path = "src/bin/selfplay.rs"

[[bin]]
name = "train"
path = "src/bin/train.rs"
