[package]
name = "wisdom"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
burn = { version = "0.16", features = ["wgpu", "ndarray", "train"] }
burn-import = "0.16"
crossbeam-channel = "0.5"
rand = "0.8"
rand_distr = "0.4"
burn-tch = "0.16"
walkdir = "2.5.0"
safetensors = "0.4"
serde_json = "1.0"
parking_lot = "0.12.5"

[[bin]]
name = "gui"
path = "src/bin/gui.rs"

[[bin]]
name = "selfplay"
path = "src/bin/selfplay.rs"



[[bin]]
name = "build_dataset"
path = "src/bin/build_dataset.rs"

[[bin]]
name = "inspect"
path = "src/bin/inspect.rs"

[[bin]]
name = "convert_mpk"
path = "src/bin/convert_mpk.rs"
